#!/usr/bin/env node
// Noviqtek School Management — one-command Cloudflare deployment.
//
//   node scripts/deploy.mjs                      deploy/upgrade production (first run creates everything)
//   node scripts/deploy.mjs --env staging        separate staging Worker + database
//   node scripts/deploy.mjs --domain school.example.qa   attach a custom domain (zone must be on Cloudflare)
//   node scripts/deploy.mjs --location eeur      D1 location hint for a NEW database (weur|eeur|apac|oc|wnam|enam)
//   node scripts/deploy.mjs --new-school         issue another one-time school setup link (multi-school)
//   node scripts/deploy.mjs --backup             export the remote database to ./backups
//   node scripts/deploy.mjs --dry-run            run all checks and a build without changing Cloudflare
//
// The script runs once on your computer; the school application is then hosted by Cloudflare
// and nothing needs to stay running locally. It never prints or stores passwords.
import { spawnSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, copyFileSync, writeFileSync, appendFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const flag = (n) => args.includes(`--${n}`);
const opt = (n, d) => { const i = args.indexOf(`--${n}`); return i >= 0 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : d; };

const ENV = opt('env', 'production');
if (!/^[a-z0-9-]{2,20}$/.test(ENV)) fail(`Invalid --env "${ENV}".`);
const WORKER = ENV === 'production' ? 'noviqtek-school' : `noviqtek-school-${ENV}`;
const DB_NAME = `noviqtek-school-${ENV}`;
const CONFIG = join(ROOT, `wrangler.${ENV}.toml`);
const DOMAIN = opt('domain', process.env.NOVIQTEK_DOMAIN || '');
const LOCATION = opt('location', '');
const STAMP = new Date().toISOString().replace(/[:.]/g, '-');
mkdirSync(join(ROOT, 'deploy-logs'), { recursive: true });
const LOG = join(ROOT, 'deploy-logs', `${ENV}-${STAMP}.log`);

const c = { g: (s) => `\x1b[32m${s}\x1b[0m`, y: (s) => `\x1b[33m${s}\x1b[0m`, r: (s) => `\x1b[31m${s}\x1b[0m`, b: (s) => `\x1b[1m${s}\x1b[0m` };
function log(msg) { console.log(msg); appendFileSync(LOG, msg.replace(/\x1b\[\d+m/g, '') + '\n'); }
function step(n, msg) { log(`\n${c.b(`[${n}]`)} ${msg}`); }
function fail(msg, hint) {
  console.error(`\n${c.r('✖ ' + msg)}${hint ? '\n  ' + hint : ''}`);
  try { appendFileSync(LOG, `FAILED: ${msg}\n${hint || ''}\n`); console.error(`  Log: ${LOG}`); } catch { /* log dir may not exist yet */ }
  process.exit(1);
}
function run(cmd, cmdArgs, { input, allowFail = false, quiet = false, interactive = false } = {}) {
  appendFileSync(LOG, `$ ${cmd} ${cmdArgs.join(' ')}\n`);
  const r = spawnSync(cmd, cmdArgs, { cwd: ROOT, input, encoding: 'utf8', shell: process.platform === 'win32', stdio: interactive ? 'inherit' : ['pipe', 'pipe', 'pipe'], env: { ...process.env, CI: interactive ? '' : '1', WRANGLER_SEND_METRICS: 'false' } });
  const out = `${r.stdout || ''}${r.stderr || ''}`;
  appendFileSync(LOG, out + '\n');
  if (r.status !== 0 && !allowFail) fail(`Command failed: ${cmd} ${cmdArgs.slice(0, 3).join(' ')} …`, (out.trim().split('\n').slice(-8).join('\n  ')) || 'See the log for details.');
  if (!quiet && out.trim() && !interactive) appendFileSync(LOG, '');
  return { ok: r.status === 0, out };
}
const wrangler = (a, o) => run('npx', ['--no-install', 'wrangler', ...a], o);
const sha256 = (s) => createHash('sha256').update(s).digest('hex');
function parseJson(out) { const i = out.search(/[[{]/); if (i < 0) return null; try { return JSON.parse(out.slice(i)); } catch { return null; } }

function writeConfig(dbId) {
  const toml = `# Generated by scripts/deploy.mjs for the "${ENV}" environment. Safe to commit (no secrets).
name = "${WORKER}"
main = "src/worker.js"
compatibility_date = "2025-09-01"
workers_dev = true
${DOMAIN ? `routes = [ { pattern = "${DOMAIN}", custom_domain = true } ]\n` : ''}
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "${DB_NAME}"
database_id = "${dbId}"
migrations_dir = "migrations"

[vars]
APP_ENV = "${ENV}"

[triggers]
crons = ["17 22 * * *"]  # nightly housekeeping (01:17 Asia/Qatar)

[observability]
enabled = true
`;
  writeFileSync(CONFIG, toml);
}

async function issueSetupLink(baseUrl) {
  const token = randomBytes(32).toString('base64url');
  const now = new Date();
  const sql = `INSERT INTO one_time_tokens (token_hash, purpose, created_at, expires_at) VALUES ('${sha256(token)}', 'school_setup', '${now.toISOString()}', '${new Date(now.getTime() + 72 * 3600e3).toISOString()}');`;
  wrangler(['d1', 'execute', DB_NAME, '--remote', '--config', CONFIG, '--command', sql]);
  return `${baseUrl}/#/setup/${token}`;
}

// ------------------------------------------------------------------
log(`${c.b('Noviqtek School Management — Cloudflare deployment')}  (env: ${ENV}, ${new Date().toISOString()})`);

step(1, 'Checking prerequisites');
const major = Number(process.versions.node.split('.')[0]);
if (major < 20) fail(`Node.js 20 or newer is required (found ${process.versions.node}).`, 'Install the LTS version from https://nodejs.org and run again.');
log(`  Node.js ${process.versions.node} ${c.g('✓')}`);
if (!existsSync(join(ROOT, 'node_modules', 'wrangler'))) {
  log('  Installing dependencies (first run only)…');
  run('npm', ['install', '--no-audit', '--no-fund']);
}
const ver = wrangler(['--version']).out.trim().split('\n').pop();
log(`  Wrangler ${ver} ${c.g('✓')}`);

step(2, 'Bundling browser libraries (QR codes, QR scanning, Excel templates)');
const vendor = join(ROOT, 'public', 'vendor');
mkdirSync(vendor, { recursive: true });
for (const [from, to] of [['qrcode-generator/qrcode.js', 'qrcode.js'], ['jsqr/dist/jsQR.js', 'jsQR.js'], ['xlsx/dist/xlsx.full.min.js', 'xlsx.full.min.js']]) {
  const src = join(ROOT, 'node_modules', from);
  if (!existsSync(src)) fail(`Missing ${from}.`, 'Run "npm install" and try again.');
  copyFileSync(src, join(vendor, to));
  log(`  ${to} ${c.g('✓')}`);
}

if (flag('dry-run')) {
  step(3, 'Dry run: validating the Worker bundle (no Cloudflare changes)');
  if (!existsSync(CONFIG)) writeConfig('00000000-0000-0000-0000-000000000000');
  wrangler(['deploy', '--dry-run', '--config', CONFIG, '--outdir', join(ROOT, '.wrangler', 'dry-run')]);
  log(c.g('\n✓ Dry run passed. Run without --dry-run to deploy.'));
  process.exit(0);
}

step(3, 'Signing in to Cloudflare');
let who = wrangler(['whoami'], { allowFail: true }).out;
if (/not authenticated|You are not logged in/i.test(who) || !/account/i.test(who)) {
  log('  A browser window will open — sign in to Cloudflare and allow Wrangler.');
  run('npx', ['--no-install', 'wrangler', 'login'], { interactive: true });
  who = wrangler(['whoami']).out;
}
log(`  Signed in ${c.g('✓')}`);

step(4, `Database (Cloudflare D1: ${DB_NAME})`);
let dbs = parseJson(wrangler(['d1', 'list', '--json']).out) || [];
let db = dbs.find((d) => d.name === DB_NAME);
let isNewDb = false;
if (!db) {
  log('  Creating database…');
  wrangler(['d1', 'create', DB_NAME, ...(LOCATION ? ['--location', LOCATION] : [])]);
  dbs = parseJson(wrangler(['d1', 'list', '--json']).out) || [];
  db = dbs.find((d) => d.name === DB_NAME);
  if (!db) fail('The database was created but could not be found.', 'Run the script again; it will reuse the existing database.');
  isNewDb = true;
}
const dbId = db.uuid || db.database_id || db.id;
log(`  ${isNewDb ? 'Created' : 'Using existing'} database ${dbId} ${c.g('✓')}`);
writeConfig(dbId);
log(`  Wrote ${CONFIG.replace(ROOT + '/', '')} ${c.g('✓')}`);

if (flag('backup')) {
  step(5, 'Exporting database backup');
  mkdirSync(join(ROOT, 'backups'), { recursive: true });
  const file = join(ROOT, 'backups', `${DB_NAME}-${STAMP}.sql`);
  wrangler(['d1', 'export', DB_NAME, '--remote', '--config', CONFIG, '--output', file]);
  log(c.g(`✓ Backup written to ${file}`) + '\n  Keep it encrypted and access-controlled: it contains personal data.');
  process.exit(0);
}

step(5, 'Safety backup and migrations');
if (!isNewDb) {
  mkdirSync(join(ROOT, 'backups'), { recursive: true });
  const file = join(ROOT, 'backups', `${DB_NAME}-pre-deploy-${STAMP}.sql`);
  const r = wrangler(['d1', 'export', DB_NAME, '--remote', '--config', CONFIG, '--output', file], { allowFail: true });
  log(r.ok ? `  Pre-deploy backup: ${file.replace(ROOT + '/', '')} ${c.g('✓')}` : c.y('  Backup export failed (continuing; D1 Time Travel still allows point-in-time restore — see docs/RUNBOOK.md).'));
}
const pending = wrangler(['d1', 'migrations', 'list', DB_NAME, '--remote', '--config', CONFIG], { allowFail: true }).out;
if (/No migrations to apply/i.test(pending)) log(`  Database schema is up to date ${c.g('✓')}`);
else { wrangler(['d1', 'migrations', 'apply', DB_NAME, '--remote', '--config', CONFIG]); log(`  Migrations applied ${c.g('✓')}`); }

step(6, 'Deploying the application (Cloudflare Worker + static assets)');
const dep = wrangler(['deploy', '--config', CONFIG]);
const urls = [...dep.out.matchAll(/https:\/\/[^\s]+/g)].map((m) => m[0]).filter((u) => /workers\.dev|\./.test(u) && !/dash\.cloudflare|developers\.cloudflare/.test(u));
const workersUrl = urls.find((u) => u.includes('workers.dev')) || urls[0];
const baseUrl = (DOMAIN ? `https://${DOMAIN}` : workersUrl || '').replace(/\/$/, '');
if (!baseUrl) fail('Deployed, but the public URL could not be read from Wrangler output.', `Open the Cloudflare dashboard → Workers & Pages → ${WORKER}. Log: ${LOG}`);
log(`  Deployed ${c.g('✓')}  ${baseUrl}`);

step(7, 'Secrets');
const secretsOut = wrangler(['secret', 'list', '--config', CONFIG], { allowFail: true }).out;
if (!/AUDIT_KEY/.test(secretsOut)) {
  wrangler(['secret', 'put', 'AUDIT_KEY', '--config', CONFIG], { input: randomBytes(32).toString('base64') + '\n' });
  log(`  Generated audit-signing key (stored only in Cloudflare) ${c.g('✓')}`);
} else log(`  Audit-signing key already set ${c.g('✓')}`);

step(8, 'Health check');
let health = null;
for (let i = 0; i < 20 && !health?.audit_key_configured; i++) {
  try { const r = await fetch(`${workersUrl || baseUrl}/api/health`); if (r.ok) health = await r.json(); } catch { /* DNS/propagation */ }
  if (!health?.audit_key_configured) await new Promise((res) => setTimeout(res, 3000));
}
if (!health) fail('The application did not answer the health check within 60 seconds.', `Try ${baseUrl}/api/health in a browser. Roll back with: npx wrangler rollback --config ${CONFIG.replace(ROOT + '/', '')}`);
log(`  API ${c.g('✓')}  database ${c.g('✓')}  audit key ${health.audit_key_configured ? c.g('✓') : c.y('pending')}`);

step(9, 'First school');
let setupLink = null;
if (flag('new-school') || !health.schools_configured) {
  setupLink = await issueSetupLink(baseUrl);
  // Printed to the screen only — never written to the log file.
  console.log(`  One-time school setup link (valid 72 hours, single use):\n\n  ${c.b(setupLink)}\n`);
  log('  Open it, create the school and first administrator, then set up two-factor authentication.');
  appendFileSync(LOG, '(setup link redacted in log)\n');
} else log('  School already configured. Use --new-school to add another school.');

log(`\n${c.g(c.b('✓ Deployment complete'))}
  App:        ${baseUrl}
  Worker:     ${WORKER}   Database: ${DB_NAME}
  Rollback:   npx wrangler rollback --config ${CONFIG.replace(ROOT + '/', '')}
  Backup:     node scripts/deploy.mjs --backup${ENV !== 'production' ? ` --env ${ENV}` : ''}
  Log:        ${LOG.replace(ROOT + '/', '')}
${DOMAIN ? '' : '  Tip: add --domain your.school.domain to serve it from your own domain.\n'}`);
